Itransition.Coursework.NextParty/WebUI/Controllers/MyEventController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebUI.Models.Entities;
using WebUI.Models.DataAccessLayer;
using WebUI.Models.Abstract;
using WebMatrix.WebData;
using WebUI.Models.Helpers;

namespace WebUI.Controllers
{
    [Authorize]
    public class MyEventController : Controller
    {
        private DataRepositories rep;

        public MyEventController()
        {
            this.rep = new DataRepositories();
        }
              
        public ActionResult OrganizedEvents()
        {
            var userId = WebSecurity.CurrentUserId;
            var events = rep.Users.GetSingle(userId).OrganizedEvents.OrderByDescending(e=>e.DatetimeOfStart);
            return View(events);
        }

        public ActionResult MyEvents()
        {
            var userId = WebSecurity.CurrentUserId;
            var events = rep.Users.GetSingle(userId).Events.OrderByDescending(e => e.DatetimeOfStart);
            return View(events);
        }
        
        public ActionResult Details(int eventId = 0)
        {
            Event ev = rep.Events.GetSingle(eventId);
            if (ev == null)
            {
                return HttpNotFound();
            }
            if (WebSecurity.CurrentUserId == ev.OrganizerID)
                return View("MyEventDetails", ev);
            return View(ev);
        }

        //
        // GET: /MyEvent/Create

        public ActionResult Create()
        {            
            return View(new WebUI.Models.Entities.Event());
        }

        //
        // POST: /MyEvent/Create

        [HttpPost]        
        public ActionResult Create(Event ev, string eventTags)
        {
            if (ModelState.IsValid)
            {                
                var tags = eventTags.Split(' ', ',');
                var alltags = rep.Tags.GetAll();
                foreach (var tag in tags)
                {
                    if (!alltags.Any(t => t.Value == tag))
                        rep.Tags.Add(new Tag() { Value = tag });
                }
                alltags = rep.Tags.GetAll(t=>tags.Any(s=>s == t.Value));
                ev.Tags = alltags.ToList();
                var user = rep.Users.GetSingle(WebSecurity.CurrentUserId);
                ev.Organizer = user;
                ev.Participants.Add(user);              
                rep.Events.Add(ev);
                return RedirectToAction("OrganizedEvents");
            }                       
            return View(ev);
        }

        //
        // GET: /MyEvent/Edit/5

        public ActionResult Edit(int eventId = 0)
        {
            Event ev = rep.Events.GetSingle(eventId);
            if (ev == null)
            {
                return HttpNotFound();
            }            
            return View(ev);
        }

        //
        // POST: /MyEvent/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Event ev)
        {
            if (ModelState.IsValid)
            {
                rep.Events.Update(ev);
                return RedirectToAction("Index");
            }            
            return View(ev);
        }

        //
        // GET: /MyEvent/Delete/5

        public ActionResult Delete(int eventId = 0)
        {
            Event ev = rep.Events.GetSingle(eventId);
            if (ev == null)
            {
                return HttpNotFound();
            }
            return View(ev);
        }

        //
        // POST: /MyEvent/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int eventId)
        {
            var ev = rep.Events.GetSingle(eventId);
            rep.Events.Remove(ev);
            return RedirectToAction("Index");
        }
        
        protected override void Dispose(bool disposing)
        {
            rep.Dispose();
            base.Dispose(disposing);
        }
    }
}

Itransition.Coursework.NextParty/WebUI/Views/Shared/_EventListPartial.cshtml
@model IEnumerable<WebUI.Models.Entities.Event>

<table class="table table-hover table-striped">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.Title)</th>            
            <th>Organizer</th>
            <th>@Html.DisplayNameFor(model => model.DatetimeOfStart)</th>
            <th>Address</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.ActionLink(item.Title, "Details", "MyEvent", new { eventId = item.EventID }, new { @class = "btn btn-default active" })</td>
                <td>@item.Organizer.UserName</td>
                <td>@item.DatetimeOfStart</td>
                <td>@item.Address</td>
                <td>
                    @if (item.Participants.Any(i => i.UserID == WebSecurity.CurrentUserId))
                    {
                        <div class="label label-success">I am participate</div>
                    }
                    else
                    { 
                        <div class="label label-danger">I am not participate</div>
                    }                
                </td>
            </tr>
        }
    </tbody>
</table>

Itransition.Coursework.NextParty/WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>@ViewBag.Title</title>        
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
        @RenderSection("head", required: false)
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("NEXT PARTY", "Index", "Home", null, new { @class = "navbar-brand" })
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>                        
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Organized events", "OrganizedEvents", "MyEvent")</li>
                        <li>@Html.ActionLink("My events", "MyEvents", "MyEvent")</li>
                        <li>@Html.ActionLink("Organize event", "Create", "MyEvent")</li>
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>
        <div class="container" style="padding-top:40px">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - vadalex</p>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    </body>
</html>