CSTraining/MvcApp/Controllers/CustomerController.cs
using System.Net;
using System.Web.Mvc;
using Contracts.BLL;
using Entities;

namespace MvcApp.Controllers
{
    [Authorize]
    public class CustomerController : BaseController
    {
        public CustomerController(IBusinessLogicLayer bll) : base(bll) { }

        // GET: Customer
        public ActionResult Index()
        {            
            return View(bll.Customers.GetAll());
        }

        // GET: Customer/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = bll.Customers.GetSingle((int)id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // GET: Customer/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Customer/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CustomerID,Name,Address,Phone")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                bll.Customers.Add(customer);                
                return RedirectToAction("Index");
            }

            return View(customer);
        }

        // GET: Customer/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = bll.Customers.GetSingle((int)id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customer/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CustomerID,Name,Address,Phone")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                bll.Customers.Update(customer);                
                return RedirectToAction("Index");
            }
            return View(customer);
        }

        // GET: Customer/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = bll.Customers.GetSingle((int)id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customer/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Customer customer = bll.Customers.GetSingle(id);
            bll.Customers.Remove(customer);            
            return RedirectToAction("Index");
        }        
    }
}

CSTraining/MvcApp/Controllers/OrderController.cs
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Entities;
using Contracts.BLL;
using MvcApp.Models;

namespace MvcApp.Controllers
{
    [Authorize]
    public class OrderController : BaseController
    {

        public OrderController(IBusinessLogicLayer bll) : base(bll) { }        
        
        // GET: Order
        public ActionResult Index()
        {            
            var orders = bll.Orders.GetAll();
            return View(orders);
        }

        // GET: Order/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = bll.Orders.GetSingle((int)id);
            if (order == null)
            {
                return HttpNotFound();
            }
            ; return View(order);
        }

        // GET: Order/Create
        public ActionResult Create()
        {
            ViewBag.CustomerID = new SelectList(bll.Customers.GetAll(), "CustomerID", "Name");
            return View();
        }

        // POST: Order/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OrderID,Status,CreatedDate,Details,CustomerID")] Order order)
        {
            if (ModelState.IsValid)
            {
                bll.Orders.Add(order);                
                return RedirectToAction("Index");
            }

            ViewBag.CustomerID = new SelectList(bll.Customers.GetAll(), "CustomerID", "Name", order.CustomerID);
            return View(order);
        }

        // GET: Order/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = bll.Orders.GetSingle((int)id);
            if (order == null)
            {
                return HttpNotFound();
            }
            //ViewBag.CustomerID = new SelectList(db.Customers, "CustomerID", "Name", order.CustomerID);            
            OrderEditModel model = new OrderEditModel();
            model.Order = order;
            model.AllProductItems = bll.Products.GetAll().Select(p => new SelectListItem { Text = p.Name, Value = p.ProductID.ToString() }).ToList();
            model.SelectedProducts = order.Products.Select(p => p.ProductID).ToList();
            model.CustomerItems = bll.Customers.GetAll().Select(c => new SelectListItem() { Text = c.Name, Value = c.CustomerID.ToString() }).ToList();
            model.CustomerItems.First(c => c.Value == order.CustomerID.ToString()).Selected = true;
            return View(model);
        }

        // POST: Order/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(OrderEditModel model)
        {            
            if (ModelState.IsValid)
            {
                foreach(int productId in model.SelectedProducts)
                {
                    var product = bll.Products.GetAll().First(p => p.ProductID == productId);
                    //db.Products.Attach(product);
                    model.Order.Products.Add(product);
                    //db.Entry<Product>(product).State = EntityState.Unchanged;
                }
                bll.Orders.Update(model.Order);                
                return RedirectToAction("Index");
            }

            model.AllProductItems = bll.Products.GetAll().Select(p => new SelectListItem { Text = p.Name, Value = p.ProductID.ToString() }).ToList();            
            model.CustomerItems = bll.Customers.GetAll().Select(c => new SelectListItem() { Text = c.Name, Value = c.CustomerID.ToString() }).ToList();
            model.CustomerItems.First(c => c.Value == model.Order.CustomerID.ToString()).Selected = true;

            return View(model);
        }

        // GET: Order/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = bll.Orders.GetSingle((int)id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Order/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Order order = bll.Orders.GetSingle(id);
            bll.Orders.Remove(order);            
            return RedirectToAction("Index");
        }
    }
}

CSTraining/MvcApp/Controllers/ProductController.cs
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Contracts.BLL;
using Entities;
using MvcApp.Models;

namespace MvcApp.Controllers
{
    [Authorize]
    public class ProductController : BaseController
    {
        public ProductController(IBusinessLogicLayer bll) : base(bll) {}

        // GET: Product
        public ActionResult Index()
        {            
            var products = bll.Products.GetAll();
            return View(products);
        }

        // GET: Product/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = bll.Products.GetSingle((int)id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Product/Create
        public ActionResult Create()
        {
            ViewBag.SupplierID = new SelectList(bll.Suppliers.GetAll(), "SupplierID", "Name");
            return View();
        }

        // POST: Product/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductID,Name,Price,Category,SupplierID")] Product product)
        {
            if (ModelState.IsValid)
            {
                bll.Products.Add(product);                
                return RedirectToAction("Index");
            }

            ViewBag.SupplierID = new SelectList(bll.Suppliers.GetAll(), "SupplierID", "Name", product.SupplierID);
            return View(product);
        }

        // GET: Product/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = bll.Products.GetSingle((int)id);
            if (product == null)
            {
                return HttpNotFound();
            }
            //ViewBag.SupplierID = new SelectList(db.Suppliers, "SupplierID", "Name", product.SupplierID);
            ProductEditModel model = new ProductEditModel();
            model.Product = product;
            model.AllOrderItems = bll.Orders.GetAll().Select(p => new SelectListItem { Text = p.Details, Value = p.OrderID.ToString() }).ToList();
            model.SelectedOrders = product.Orders.Select(p => p.OrderID).ToList();
            model.SupplierItems = bll.Suppliers.GetAll().Select(c => new SelectListItem() { Text = c.Name, Value = c.SupplierID.ToString() }).ToList();
            model.SupplierItems.First(c => c.Value == product.SupplierID.ToString()).Selected = true;
            return View(model);
        }

        // POST: Product/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ProductEditModel model)
        {
            if (ModelState.IsValid)
            {
                foreach (int orderId in model.SelectedOrders)
                {
                    var order = bll.Orders.GetAll().First(p => p.OrderID == orderId);
                    model.Product.Orders.Add(order);
                }
                bll.Products.Update(model.Product);
                return RedirectToAction("Index");
            }
            model.AllOrderItems = bll.Orders.GetAll().Select(p => new SelectListItem { Text = p.Details, Value = p.OrderID.ToString() }).ToList();            
            model.SupplierItems = bll.Suppliers.GetAll().Select(c => new SelectListItem() { Text = c.Name, Value = c.SupplierID.ToString() }).ToList();
            model.SupplierItems.First(c => c.Value == model.Product.SupplierID.ToString()).Selected = true;
            return View(model);
        }

        // GET: Product/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = bll.Products.GetSingle((int)id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Product/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = bll.Products.GetSingle(id);
            bll.Products.Remove(product);            
            return RedirectToAction("Index");
        }
    }
}

CSTraining/MvcApp/Controllers/SupplierController.cs
using System.Net;
using System.Web.Mvc;
using Contracts.BLL;
using Entities;

namespace MvcApp.Controllers
{
    
    public class SupplierController : BaseController    
    {
                
        public SupplierController(IBusinessLogicLayer bll) : base(bll) {}

        // GET: Supplier
        public ActionResult Index()//BusinessLogicLayer bll)
        {            
            return View(bll.Suppliers.GetAll());
        }

        // GET: Supplier/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Supplier supplier = bll.Suppliers.GetSingle((int)id);
            if (supplier == null)
            {
                return HttpNotFound();
            }
            return View(supplier);
        }

        // GET: Supplier/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Supplier/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SupplierID,Name,Phone,Details")] Supplier supplier)
        {
            if (ModelState.IsValid)
            {
                bll.Suppliers.Add(supplier);
                return RedirectToAction("Index");
            }

            return View(supplier);
        }

        // GET: Supplier/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Supplier supplier = bll.Suppliers.GetSingle((int)id);
            if (supplier == null)
            {
                return HttpNotFound();
            }
            return View(supplier);
        }

        // POST: Supplier/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SupplierID,Name,Phone,Details")] Supplier supplier)
        {
            if (ModelState.IsValid)
            {
                bll.Suppliers.Update(supplier);
                return RedirectToAction("Index");
            }
            return View(supplier);
        }

        // GET: Supplier/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Supplier supplier = bll.Suppliers.GetSingle((int)id);
            if (supplier == null)
            {
                return HttpNotFound();
            }
            return View(supplier);
        }

        // POST: Supplier/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Supplier supplier = bll.Suppliers.GetSingle(id);
            bll.Suppliers.Remove(supplier);            
            return RedirectToAction("Index");
        }
    }
}

CSTraining/MvcApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<article>
    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>
</article>

<aside>
    <h3>Aside Title</h3>
    <p>
        Use this area to provide additional information.
    </p>
    <ul>
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
    </ul>
</aside>

CSTraining/MvcApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<section class="contact">
    <header>
        <h3>Phone</h3>
    </header>
    <p>
        <span class="label">Main:</span>
        <span>425.555.0100</span>
    </p>
    <p>
        <span class="label">After Hours:</span>
        <span>425.555.0199</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Email</h3>
    </header>
    <p>
        <span class="label">Support:</span>
        <span><a href="mailto:Support@example.com">Support@example.com</a></span>
    </p>
    <p>
        <span class="label">Marketing:</span>
        <span><a href="mailto:Marketing@example.com">Marketing@example.com</a></span>
    </p>
    <p>
        <span class="label">General:</span>
        <span><a href="mailto:General@example.com">General@example.com</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Address</h3>
    </header>
    <p>
        One Microsoft Way<br />
        Redmond, WA 98052-6399
    </p>
</section>

CSTraining/MvcApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>ASP.NET MVC.</h1>
            </hgroup>
            <p>
                To learn more about ASP.NET MVC visit
                <a href="http://asp.net/mvc" title="ASP.NET MVC Website">http://asp.net/mvc</a>.
                The page features <mark>videos, tutorials, and samples</mark> to help you get the most from ASP.NET MVC.
                If you have any questions about ASP.NET MVC visit
                <a href="http://forums.asp.net/1146.aspx/1?MVC" title="ASP.NET MVC Forum">our forums</a>.
            </p>
        </div>
    </section>
}

<h3>We suggest the following:</h3>
<ol class="round">
    <li class="one">
        <h4>@Html.ActionLink("Suppliers", "Index", "Supplier")</h4>
    </li>
    <li class="two">
        <h4>@Html.ActionLink("Products", "Index", "Product")</h4>
    </li>
    <li class="three">
        <h4>@Html.ActionLink("Orders", "Index", "Order")</h4>
    </li>
    <li class="four">
        <h4>@Html.ActionLink("Customers", "Index", "Customer")</h4>
    </li>
</ol>

CSTraining/MvcApp/Views/Home/MyOrders.cshtml
@model IEnumerable<Entities.Order>

@{
    ViewBag.Title = "MyOrders";
}

<h2>My orders</h2>

<table class="table">
    <tr>
        <th>
            Customer
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Details)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Amount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsPaid)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PayerId)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Customer.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Details)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Amount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsPaid)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PayerId)
            </td>
        </tr>
    }

</table>

CSTraining/MvcApp/Views/Home/SearchResult.cshtml
@model BusinessLogic.Search.SearchResult

@{
    ViewBag.Title = "SearchResult";
}

<h2>Search results for ' <span style="font-style:italic">@Model.KeyWords</span> ' </h2>

@if (Model.Products.Any()) 
{     
    <hr/>
    <h4>In products:</h4>
<table class="table">
    <tr>
        <th>
            ID
        </th>        
        <th>
            Name
        </th>        
        <th>
            Price
        </th>
        <th>
            Category
        </th>        
    </tr>

    @foreach (var item in Model.Products)
    {
        <tr>
            <td>
                @Html.ActionLink(item.ProductID.ToString(), "Details", "Product", new { id = item.ProductID }, new { } )
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>        
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category)
            </td>            
        </tr>
    }    
</table>
} 

@if (Model.Suppliers.Any())
{
    <hr />
    <h4>In suppliers:</h4>
    <table class="table">
        <tr>
            <th>
                ID
            </th>
            <th>
                Name
            </th>
            <th>
                Details
            </th>             
        </tr>

        @foreach (var item in Model.Suppliers)
        {
            <tr>
                <td>
                    @Html.ActionLink(item.SupplierID.ToString(), "Details", "Supplier", new { id = item.SupplierID}, new { })
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Details)
                </td>              
            </tr>
        }
    </table>
} 

@if (Model.Orders.Any())
{
    <hr />
    <h4>In orders:</h4>
    <table class="table">
        <tr>
            <th>
                ID
            </th>
            <th>
                Details
            </th>
            <th>
                CustomerID
            </th>            
        </tr>

        @foreach (var item in Model.Orders)
        {
            <tr>
                <td>
                    @Html.ActionLink(item.OrderID.ToString(), "Details", "Order", new { id = item.OrderID }, new { })
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Details)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CustomerID)
                </td> 
            </tr>
        }
    </table>
} 

@if (Model.Customers.Any())
{
    <hr />
    <h4>In customers:</h4>
    <table class="table">
        <tr>
            <th>
                ID
            </th>
            <th>
                Name
            </th>
            <th>
                Address
            </th>            
        </tr>

        @foreach (var item in Model.Customers)
        {
            <tr>
                <td>
                    @Html.ActionLink(item.CustomerID.ToString(), "Details", "Customer", new { id = item.CustomerID }, new { })
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
            </tr>
        }
    </table>
} 